[versions]
compileSdk = "34"
minSdk = "21"
targetSdk = "34"
appCompat = "1.3.1"
core = "1.10.1"
constraintLayout = "2.1.1"
material = "1.9.0"
navigation = "2.6.0"
recyclerView = "1.2.1"
koin = "3.1.2"
room = "2.5.2"
coroutines = "1.5.1"
okhttp3BOM = "4.9.3"
sdpssp = "1.0.6"
swipeRefresh = "1.1.0"
paging = "3.1.1"
fuel = "2.3.1"
moshi = "1.12.0"
coil = "0.7.0"
junit = "4.+"
testExtJunit = "1.1.3"
espresso = "3.4.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }

material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-navigation-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compat = { module = "io.insert-koin:koin-android-compat", version.ref = "koin" }
room-kapt = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp3BOM" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
sdp = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpssp" }
ssp = { module = "com.intuit.ssp:ssp-android", version.ref = "sdpssp" }
androidx-swipe-refresh = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipeRefresh" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
fuel = { module = "com.github.kittinunf.fuel:fuel", version.ref = "fuel" }
fuel-coroutines = { module = "com.github.kittinunf.fuel:fuel-coroutines", version.ref = "fuel" }
fuel-moshi = { module = "com.github.kittinunf.fuel:fuel-moshi", version.ref = "fuel" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "testExtJunit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }